///////////////////////////////////////////////////////////
//  MainFormConfig.cs
//  Implementation of the Class MainFormConfig
//  Generated by Enterprise Architect
//  Created on:      06-五月-2013 17:16:32
//  Original author: wfp
///////////////////////////////////////////////////////////




namespace AutoSign {
	/// <summary>
	/// 主窗体配置参数
	/// </summary>
	public class MainFormConfig {

		/// <summary>
		/// 窗体高度
		/// </summary>
		private int m_Height;
		/// <summary>
		/// 主窗体是否最大化
		/// </summary>
		private bool m_Maximized;
		/// <summary>
		/// 窗体宽度
		/// </summary>
		private int m_Width;

		public MainFormConfig(){

		}

		~MainFormConfig(){

		}

		public virtual void Dispose(){

		}

		/// <summary>
		/// 窗体高度
		/// </summary>
		public int Height{
			get{
				return m_Height;
			}
			set{
				m_Height = value;
			}
		}

		/// <summary>
		/// 主窗体是否最大化
		/// </summary>
		public bool Maximized{
			get{
				return m_Maximized;
			}
			set{
				m_Maximized = value;
			}
		}

		/// <summary>
		/// 窗体宽度
		/// </summary>
		public int Width{
			get{
				return m_Width;
			}
			set{
				m_Width = value;
			}
		}

	}//end MainFormConfig

}//end namespace AutoSign